version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    pre_build:
      - git fetch --unshallow || true
      - git submodule update --init --recursive || true
    build:
      - pip install -e .
      - mkdocs build --site-dir $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .
